<a href="https://colab.research.google.com/github/Sonuthahreen/coding-part-of-pytorch/blob/main/module1_fundamentals_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

resource:https://www.youtube.com/watch?v=V_xro1bcAuA

In [1]:
print("lets start the joruney with BIRBLE AI")

lets start the joruney with BIRBLE AI


In [2]:
!nvidia-smi

Thu Feb  8 16:25:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


In [4]:
!nvidia-smi

Thu Feb  8 16:37:14 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

##INTRODUCTION TO TENSOR
**CREATING TENSORS**
pytorch tensors are created using 'torch.tensor()'



In [4]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#get tensor back as python int
scalar.item()

7

In [7]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
#vector define as usually have magnitude and direction

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [11]:
#creation of MATRIX
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix.shape

torch.Size([2, 2])

In [16]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],[3,4,5],[6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

###Random Tensors
why random tensors?

Random Tensors are important because the way many neural networks learns is they start with tensors full of random numbers and then adjust those random numbers to better represent the data
start with random numbers ->look at data -> update random numbers -> look at the data ->update random numbers

In [20]:
#creating a random tensor of size (3,4)#practice
random_tensor=torch.rand(30,30)
random_tensor

tensor([[3.9988e-01, 8.9506e-01, 4.5341e-01, 1.6763e-01, 4.3803e-01, 9.8105e-01,
         4.1389e-01, 1.9590e-01, 5.5549e-01, 8.0917e-01, 9.4275e-01, 1.7622e-01,
         6.6054e-01, 9.2125e-02, 7.1536e-01, 6.8763e-01, 7.8527e-01, 7.5123e-01,
         8.8107e-01, 2.5435e-01, 6.0708e-01, 6.8827e-01, 3.0037e-01, 6.2505e-01,
         5.2560e-01, 1.7654e-01, 7.2473e-01, 4.9500e-01, 7.6655e-01, 3.3049e-01],
        [2.5099e-01, 2.8646e-01, 3.1247e-01, 8.5567e-02, 3.8446e-01, 2.7923e-01,
         4.3674e-01, 1.7944e-02, 7.8164e-01, 6.5335e-02, 6.4047e-01, 2.6574e-01,
         5.5575e-01, 2.0213e-01, 4.9421e-01, 5.2114e-01, 8.1278e-01, 9.3961e-01,
         4.3596e-01, 1.3362e-01, 3.0770e-01, 9.3124e-01, 7.8229e-01, 2.7051e-01,
         6.1654e-01, 7.3805e-01, 6.5766e-01, 6.7684e-01, 6.7309e-01, 7.9082e-01],
        [6.0187e-01, 2.5093e-01, 6.1785e-01, 7.3076e-01, 5.9613e-01, 4.8587e-01,
         2.5980e-01, 3.7018e-02, 2.3867e-01, 3.4697e-01, 5.0313e-01, 3.9782e-01,
         9.9942e-01, 1.079

In [21]:
random_tensor.ndim

2

In [26]:
#creating a random tensor with similar shape to an image
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [27]:
#creating a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
#creating a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

In [30]:
#practice
#creating a tensor of all zeros
zeros=torch.zeros(size=(10,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [31]:
#creating a tensor of all ones
ones=torch.ones(size=(3,10))
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

creating a range of tensors and tensors-like

In [37]:
#use torch.range()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Dealing with tensor datatpes

here are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which is which can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

In [40]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [41]:
float_32_tensor.dtype

torch.float32

**NOTE**:Tensor datatypes is one of the 3big errors we will run into with pytorch and deep learning(DL)
1.Tensors not right datatype
2.tensors not right shape
3.Tenors not on the right device